import Head from "next/head";
import { useState } from "react";
import Robot from "../components/Robot";

export default function Home() {
  const [X, setX] = useState()

  return (
    <div className="bg-black h-screen text-white">
      <Head>
        <title>Next.js toy robot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Robot/>
    </div>
  );
}
